env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    -
      FunctionExpression:
        parameters: first
      ArrayExpression: first
      ObjectExpression: first
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
